# Generated by Django 3.0.3 on 2020-06-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascgen1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmyfiles',
            name='upload_file',
            field=models.FileField(upload_to='profiles'),
        ),
    ]
